#!/bin/bash
# Compile all DSL examples to Berry scripts
# This script reads each DSL example in anim_examples/ and produces transpiled Berry scripts in anim_examples/compiled/

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
EXAMPLES_DIR="lib/libesp32/berry_animation/anim_examples"
OUTPUT_DIR="lib/libesp32/berry_animation/anim_examples/compiled"
BERRY_CMD="./berry -s -g -m lib/libesp32/berry_animation/src"
SUMMARY_FILE="$OUTPUT_DIR/compilation_summary.md"

# Statistics
TOTAL_FILES=0
SUCCESSFUL=0
FAILED=0

# Arrays to store compilation results
declare -a SUCCESSFUL_FILES
declare -a FAILED_FILES
declare -a COMPILATION_OUTPUTS

echo -e "${BLUE}DSL Example Compilation Script${NC}"
echo "=============================="

# Check if berry executable exists
if [ ! -f "./berry" ]; then
    echo -e "${RED}Error: Berry executable not found. Please run 'make' first.${NC}"
    exit 1
fi

# Check if examples directory exists
if [ ! -d "$EXAMPLES_DIR" ]; then
    echo -e "${RED}Error: Examples directory '$EXAMPLES_DIR' not found.${NC}"
    exit 1
fi

# Create output directory and clear existing files
if [ ! -d "$OUTPUT_DIR" ]; then
    mkdir -p "$OUTPUT_DIR"
    echo -e "${GREEN}Created output directory: $OUTPUT_DIR${NC}"
else
    # Clear existing compiled files
    echo -e "${YELLOW}Clearing existing compiled files in $OUTPUT_DIR${NC}"
    rm -f "$OUTPUT_DIR"/*.be
    rm -f "$OUTPUT_DIR"/run_tests.sh
    rm -f "$OUTPUT_DIR"/compilation_summary.md
fi

# Initialize summary file
cat > "$SUMMARY_FILE" << EOF
# DSL Compilation Summary

## Overview

This document contains a summary of the DSL compilation process, including symbol tables and compilation outputs for all processed files.

EOF

# Count DSL files (sorted alphabetically by filename)
DSL_FILES=($(find "$EXAMPLES_DIR" -name "*.anim" -type f | sort))
TOTAL_FILES=${#DSL_FILES[@]}

if [ $TOTAL_FILES -eq 0 ]; then
    echo -e "${YELLOW}No DSL files found in $EXAMPLES_DIR directory${NC}"
    exit 1
fi

echo "Found $TOTAL_FILES DSL files to compile"
echo ""

# Function to compile a single DSL file
compile_dsl_file() {
    local input_file="$1"
    local filename=$(basename "$input_file")
    local base_name="${filename%.anim}"
    local output_file="$OUTPUT_DIR/${base_name}.be"
    
    echo -n "Compiling $filename... "
    
    # Create a temporary Berry script to do the compilation
    local temp_script=$(mktemp)
    cat > "$temp_script" << EOF
import sys
sys.path().push("lib/libesp32/berry_animation/src")
import tasmota
def log(x,l) tasmota.log(x,l) end
import animation
import animation_dsl
import user_functions
import string

# Read DSL source
var f = open("$input_file", "r")
var dsl_source = f.read()
f.close()

# Compile DSL to Berry code and get symbol table information
var lexer = animation_dsl.create_lexer(dsl_source, false)
var transpiler = animation_dsl.SimpleDSLTranspiler(lexer)
var berry_code = transpiler.transpile()

if berry_code == nil
  print("DSL compilation failed")
  import os
  os.exit(1)
end

# Get symbol table report
var symbol_report = transpiler.get_symbol_table_report()

# Generate header (without original source)
var header = "# Generated Berry code from Animation DSL\\n" +
             "# Source: $filename\\n" +
             "# \\n" +
             "# This file was automatically generated by compile_all_examples.sh\\n" +
             "# Do not edit manually - changes will be overwritten\\n" +
             "\\n"

# Generate footer with original DSL source as multi-line comment
var footer = "\\n\\n#- Original DSL source:\\n" + dsl_source + "\\n-#\\n"

# Write complete file
var output = open("$output_file", "w")
output.write(header + berry_code + footer)
output.close()

print("SUCCESS")
EOF
    
    # Create temp files for capturing outputs
    local temp_symbol_report=$(mktemp)
    
    # Modify the Berry script to also write symbol table to temp file
    cat >> "$temp_script" << EOF

# Write symbol table report to temp file for summary
var symbol_file = open("$temp_symbol_report", "w")
symbol_file.write(symbol_report)
symbol_file.close()
EOF
    
    # Run the compilation and capture output
    local compilation_output
    if compilation_output=$($BERRY_CMD "$temp_script" 2>&1); then
        echo -e "${GREEN}✓${NC}"
        ((SUCCESSFUL++))
        SUCCESSFUL_FILES+=("$filename")
        
        # Add to summary file
        {
            echo "## $filename"
            echo ""
            echo "**Status:** ✅ Success"
            echo ""
            if [ -f "$temp_symbol_report" ]; then
                cat "$temp_symbol_report"
            fi
            echo "### Compilation Output"
            echo ""
            echo '```'
            echo "$compilation_output"
            echo '```'
            echo ""
        } >> "$SUMMARY_FILE"
    else
        echo -e "${RED}✗${NC}"
        ((FAILED++))
        FAILED_FILES+=("$filename")
        
        # Try to get error details and show them
        echo -e "${RED}  Error details:${NC}"
        echo "$compilation_output" | sed 's/^/    /'
        
        # Add to summary file
        {
            echo "## $filename"
            echo ""
            echo "**Status:** ❌ Failed"
            echo ""
            echo "### Compilation Output"
            echo ""
            echo '```'
            echo "$compilation_output"
            echo '```'
            echo ""
        } >> "$SUMMARY_FILE"
    fi
    
    # Clean up temp files
    rm -f "$temp_script" "$temp_symbol_report"
}

# Compile all DSL files
for dsl_file in "${DSL_FILES[@]}"; do
    compile_dsl_file "$dsl_file"
done

# Create a test runner script
cat > "$OUTPUT_DIR/run_tests.sh" << 'EOF'
#!/bin/bash
# Test runner for compiled DSL examples
# Generated automatically by compile_all_examples.sh

set -e

BERRY_CMD="./berry -s -g -m lib/libesp32/berry_animation/src -e 'import tasmota def log(x,l) tasmota.log(x,l) end '"
COMPILED_DIR="lib/libesp32/berry_animation/anim_examples/compiled"

echo "Running compiled DSL examples..."
echo "==============================="

SUCCESS_COUNT=0
TOTAL_COUNT=0

for berry_file in "$COMPILED_DIR"/*.be; do
    if [ -f "$berry_file" ]; then
        filename=$(basename "$berry_file")
        echo -n "Testing $filename... "
        
        ((TOTAL_COUNT++))
        
        if eval "$BERRY_CMD \"$berry_file\"" > /dev/null 2>&1; then
            echo "✓"
            ((SUCCESS_COUNT++))
        else
            echo "✗"
            echo "  Error details:"
            eval "$BERRY_CMD \"$berry_file\"" 2>&1 | sed 's/^/    /'
        fi
    fi
done

echo ""
echo "Test Results: $SUCCESS_COUNT/$TOTAL_COUNT examples ran successfully"
EOF

chmod +x "$OUTPUT_DIR/run_tests.sh"
echo -e "${BLUE}Created test runner: $OUTPUT_DIR/run_tests.sh${NC}"

# Complete the summary file
{
    echo "## Summary"
    echo ""
    echo "- **Total files processed:** $TOTAL_FILES"
    echo "- **Successfully compiled:** $SUCCESSFUL"
    echo "- **Failed to compile:** $FAILED"
    echo ""
    if [ $SUCCESSFUL -gt 0 ]; then
        echo "### Successful Files"
        echo ""
        for file in "${SUCCESSFUL_FILES[@]}"; do
            echo "- ✅ $file"
        done
        echo ""
    fi
    if [ $FAILED -gt 0 ]; then
        echo "### Failed Files"
        echo ""
        for file in "${FAILED_FILES[@]}"; do
            echo "- ❌ $file"
        done
        echo ""
    fi
    echo "---"
    echo ""
} >> "$SUMMARY_FILE"

echo -e "${BLUE}Created compilation summary: $SUMMARY_FILE${NC}"

# Print final statistics
echo ""
echo "=================================================="
echo -e "${BLUE}COMPILATION SUMMARY${NC}"
echo "=================================================="
echo "Total files processed: $TOTAL_FILES"
echo -e "Successfully compiled: ${GREEN}$SUCCESSFUL${NC}"
echo -e "Failed to compile: ${RED}$FAILED${NC}"

if [ $FAILED -gt 0 ]; then
    echo ""
    echo -e "${YELLOW}Some files failed to compile. Check the error messages above.${NC}"
fi

if [ $SUCCESSFUL -gt 0 ]; then
    echo ""
    echo -e "${GREEN}Compiled files are available in the '$OUTPUT_DIR' directory${NC}"
    echo -e "${BLUE}Run '$OUTPUT_DIR/run_tests.sh' to test the compiled examples${NC}"
fi

echo "=================================================="

# Exit with appropriate code
if [ $FAILED -gt 0 ]; then
    echo -e "${RED}Compilation completed with errors${NC}"
    exit 1
else
    echo -e "${GREEN}All files compiled successfully!${NC}"
    exit 0
fi