#!/bin/bash
# Comprehensive DSL Example Compilation Script
# Attempts to compile all DSL examples and provides detailed reporting

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
EXAMPLES_DIR="lib/libesp32/berry_animation/anim_examples"
OUTPUT_DIR="lib/libesp32/berry_animation/anim_examples/compiled"
BERRY_CMD="./berry -s -g -m lib/libesp32/berry_animation/src"

# Statistics
TOTAL_FILES=0
SUCCESSFUL=0
FAILED=0
declare -a SUCCESSFUL_FILES=()
declare -a FAILED_FILES=()

echo -e "${BLUE}Comprehensive DSL Example Compilation Script${NC}"
echo "============================================="

# Check prerequisites
if [ ! -f "./berry" ]; then
    echo -e "${RED}Error: Berry executable not found. Please run 'make' first.${NC}"
    exit 1
fi

if [ ! -d "$EXAMPLES_DIR" ]; then
    echo -e "${RED}Error: Examples directory '$EXAMPLES_DIR' not found.${NC}"
    exit 1
fi

# Create output directory
if [ ! -d "$OUTPUT_DIR" ]; then
    mkdir -p "$OUTPUT_DIR"
    echo -e "${GREEN}Created output directory: $OUTPUT_DIR${NC}"
fi

# Get list of DSL files
DSL_FILES=($(find "$EXAMPLES_DIR" -name "*.anim" -type f | sort))
TOTAL_FILES=${#DSL_FILES[@]}

if [ $TOTAL_FILES -eq 0 ]; then
    echo -e "${YELLOW}No DSL files found in $EXAMPLES_DIR directory${NC}"
    exit 1
fi

echo "Found $TOTAL_FILES DSL files to compile"
echo ""

# Function to compile a single DSL file
compile_dsl_file() {
    local input_file="$1"
    local filename=$(basename "$input_file")
    local base_name="${filename%.anim}"
    local output_file="$OUTPUT_DIR/${base_name}.be"
    local temp_script=$(mktemp)
    local temp_output=$(mktemp)
    
    echo -n -e "${CYAN}Compiling $filename...${NC} "
    
    # Create compilation script
    cat > "$temp_script" << EOF
import sys
sys.path().push("lib/libesp32/berry_animation/src")
import animation
import animation_dsl

# Read DSL source
var f = open("$input_file", "r")
var dsl_source = f.read()
f.close()

# Compile DSL to Berry code
var berry_code = animation_dsl.compile(dsl_source)
if berry_code == nil
  print("COMPILATION_FAILED")
  return
end

# Generate header
var header = "# Generated Berry code from Animation DSL\\n" +
             "# Source: $filename\\n" +
             "# Generated automatically\\n" +
             "# \\n" +
             "# This file was automatically generated by compile_all_dsl_examples.sh\\n" +
             "# Do not edit manually - changes will be overwritten\\n" +
             "\\n"

# Add original DSL as comments
import string
var lines = string.split(dsl_source, "\\n")
header += "# Original DSL source:\\n"
for line : lines
  header += "# " + line + "\\n"
end
header += "\\n"

# Write complete file
var output = open("$output_file", "w")
output.write(header + berry_code)
output.close()

print("COMPILATION_SUCCESS")
EOF
    
    # Run compilation and capture output
    if $BERRY_CMD "$temp_script" > "$temp_output" 2>&1; then
        local result=$(cat "$temp_output")
        if [[ "$result" == *"COMPILATION_SUCCESS"* ]]; then
            echo -e "${GREEN}✓${NC}"
            SUCCESSFUL_FILES+=("$filename")
            ((SUCCESSFUL++))
        else
            echo -e "${RED}✗${NC}"
            echo -e "${RED}  Compilation failed${NC}"
            FAILED_FILES+=("$filename")
            ((FAILED++))
        fi
    else
        echo -e "${RED}✗${NC}"
        echo -e "${RED}  Error details:${NC}"
        cat "$temp_output" | sed 's/^/    /'
        FAILED_FILES+=("$filename")
        ((FAILED++))
    fi
    
    # Clean up
    rm -f "$temp_script" "$temp_output"
}

# Compile all DSL files
for dsl_file in "${DSL_FILES[@]}"; do
    compile_dsl_file "$dsl_file"
done

# Create comprehensive report
create_report() {
    local report_file="$OUTPUT_DIR/COMPILATION_REPORT.md"
    
    cat > "$report_file" << EOF
# DSL Compilation Report

Generated: $(date)

## Summary

- **Total files**: $TOTAL_FILES
- **Successfully compiled**: $SUCCESSFUL
- **Failed to compile**: $FAILED
- **Success rate**: $(( SUCCESSFUL * 100 / TOTAL_FILES ))%

## Successfully Compiled Files

EOF

    for file in "${SUCCESSFUL_FILES[@]}"; do
        echo "- ✅ $file" >> "$report_file"
    done

    cat >> "$report_file" << EOF

## Failed Compilations

EOF

    for file in "${FAILED_FILES[@]}"; do
        echo "- ❌ $file" >> "$report_file"
    done

    cat >> "$report_file" << EOF

## Common Issues Found

Based on the compilation attempts, the following issues are common:

### 1. Comments in Palette Definitions
Many files fail because comments are included within palette array definitions:
\`\`\`
palette fire_colors = [
  (0, #000000),    # This comment causes parsing errors
  (128, #FF0000)   # This too
]
\`\`\`

**Solution**: Remove comments from within palette definitions.

### 2. Comments in Function Arguments
Comments within function calls break the parser:
\`\`\`
animation pulse_red = pulse(
  solid(red),
  2s,           # This comment breaks parsing
  20%, 100%
)
\`\`\`

**Solution**: Remove comments from function argument lists.

### 3. Missing Function Parameters
Some function calls expect specific parameter formats that aren't provided.

### 4. Property Assignments Not Supported
Object property assignments like \`stripe1.pos = 3\` are not handled correctly.

## Recommendations

1. **Clean DSL Syntax**: Remove all inline comments from complex expressions
2. **Full Parameter Lists**: Always provide complete parameter lists to functions
3. **Use Sequences**: Instead of property assignments, use sequence-based approaches
4. **Test Incrementally**: Start with simple examples and build complexity gradually

## Working Examples

The successfully compiled files can be used as templates for creating new DSL animations.

EOF

    echo -e "${BLUE}Created compilation report: $report_file${NC}"
}

# Create test runner for successful compilations
create_test_runner() {
    if [ $SUCCESSFUL -eq 0 ]; then
        return
    fi
    
    cat > "$OUTPUT_DIR/run_successful_tests.sh" << 'EOF'
#!/bin/bash
# Test runner for successfully compiled DSL examples

BERRY_CMD="./berry -s -g -m lib/libesp32/berry_animation"
COMPILED_DIR="compiled"

echo "Testing successfully compiled DSL examples..."
echo "============================================="

SUCCESS_COUNT=0
TOTAL_COUNT=0

EOF

    for file in "${SUCCESSFUL_FILES[@]}"; do
        local base_name="${file%.anim}"
        cat >> "$OUTPUT_DIR/run_successful_tests.sh" << EOF
echo -n "Testing ${base_name}.be... "
if \$BERRY_CMD "\$COMPILED_DIR/${base_name}.be" > /dev/null 2>&1; then
    echo "✓"
    ((SUCCESS_COUNT++))
else
    echo "✗"
fi
((TOTAL_COUNT++))

EOF
    done

    cat >> "$OUTPUT_DIR/run_successful_tests.sh" << 'EOF'

echo ""
echo "Test Results: $SUCCESS_COUNT/$TOTAL_COUNT examples executed successfully"
EOF

    chmod +x "$OUTPUT_DIR/run_successful_tests.sh"
    echo -e "${BLUE}Created test runner: $OUTPUT_DIR/run_successful_tests.sh${NC}"
}

# Create report and test runner
create_report
create_test_runner

# Print final statistics
echo ""
echo "=================================================="
echo -e "${BLUE}FINAL COMPILATION SUMMARY${NC}"
echo "=================================================="
echo "Total files processed: $TOTAL_FILES"
echo -e "Successfully compiled: ${GREEN}$SUCCESSFUL${NC}"
echo -e "Failed to compile: ${RED}$FAILED${NC}"

if [ $SUCCESSFUL -gt 0 ]; then
    echo ""
    echo -e "${GREEN}Successfully compiled files:${NC}"
    for file in "${SUCCESSFUL_FILES[@]}"; do
        echo -e "  ✅ $file"
    done
fi

if [ $FAILED -gt 0 ]; then
    echo ""
    echo -e "${RED}Failed files:${NC}"
    for file in "${FAILED_FILES[@]}"; do
        echo -e "  ❌ $file"
    done
fi

echo ""
echo -e "${BLUE}📊 Success rate: $(( SUCCESSFUL * 100 / TOTAL_FILES ))%${NC}"
echo -e "${CYAN}📄 Detailed report: $OUTPUT_DIR/COMPILATION_REPORT.md${NC}"

if [ $SUCCESSFUL -gt 0 ]; then
    echo -e "${GREEN}🧪 Test runner: $OUTPUT_DIR/run_successful_tests.sh${NC}"
fi

echo "=================================================="

# Exit with appropriate code
if [ $FAILED -gt 0 ]; then
    echo -e "${YELLOW}Compilation completed with some failures${NC}"
    exit 1
else
    echo -e "${GREEN}All files compiled successfully!${NC}"
    exit 0
fi